// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
#![doc = "generated by AutoRust 0.1.0"]
#![allow(non_camel_case_types)]
#![allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditActionInfo {
    #[serde(rename = "actionId", default, skip_serializing_if = "Option::is_none")]
    pub action_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub area: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<audit_action_info::Category>,
}
pub mod audit_action_info {
    use super::*;
    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub enum Category {
        #[serde(rename = "unknown")]
        Unknown,
        #[serde(rename = "modify")]
        Modify,
        #[serde(rename = "remove")]
        Remove,
        #[serde(rename = "create")]
        Create,
        #[serde(rename = "access")]
        Access,
        #[serde(rename = "execute")]
        Execute,
    }
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditLogEntry {
    #[serde(rename = "actionId", default, skip_serializing_if = "Option::is_none")]
    pub action_id: Option<String>,
    #[serde(
        rename = "activityId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub activity_id: Option<String>,
    #[serde(rename = "actorCUID", default, skip_serializing_if = "Option::is_none")]
    pub actor_cuid: Option<String>,
    #[serde(rename = "actorUPN", default, skip_serializing_if = "Option::is_none")]
    pub actor_upn: Option<String>,
    #[serde(
        rename = "actorUserId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub actor_user_id: Option<String>,
    #[serde(
        rename = "authenticationMechanism",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub authentication_mechanism: Option<String>,
    #[serde(
        rename = "correlationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub correlation_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "ipAddress", default, skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[serde(rename = "projectId", default, skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(rename = "scopeId", default, skip_serializing_if = "Option::is_none")]
    pub scope_id: Option<String>,
    #[serde(rename = "scopeType", default, skip_serializing_if = "Option::is_none")]
    pub scope_type: Option<audit_log_entry::ScopeType>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "userAgent", default, skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
}
pub mod audit_log_entry {
    use super::*;
    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub enum ScopeType {
        #[serde(rename = "unknown")]
        Unknown,
        #[serde(rename = "deployment")]
        Deployment,
        #[serde(rename = "enterprise")]
        Enterprise,
        #[serde(rename = "organization")]
        Organization,
        #[serde(rename = "project")]
        Project,
    }
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditLogQueryResult {
    #[serde(
        rename = "continuationToken",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub continuation_token: Option<String>,
    #[serde(
        rename = "decoratedAuditLogEntries",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub decorated_audit_log_entries: Vec<DecoratedAuditLogEntry>,
    #[serde(rename = "hasMore", default, skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditStream {
    #[serde(
        rename = "consumerInputs",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub consumer_inputs: Option<serde_json::Value>,
    #[serde(
        rename = "consumerType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub consumer_type: Option<String>,
    #[serde(
        rename = "createdTime",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub created_time: Option<String>,
    #[serde(
        rename = "displayName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<audit_stream::Status>,
    #[serde(
        rename = "statusReason",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub status_reason: Option<String>,
    #[serde(
        rename = "updatedTime",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub updated_time: Option<String>,
}
pub mod audit_stream {
    use super::*;
    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub enum Status {
        #[serde(rename = "unknown")]
        Unknown,
        #[serde(rename = "enabled")]
        Enabled,
        #[serde(rename = "disabledByUser")]
        DisabledByUser,
        #[serde(rename = "disabledBySystem")]
        DisabledBySystem,
        #[serde(rename = "deleted")]
        Deleted,
        #[serde(rename = "backfilling")]
        Backfilling,
    }
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecoratedAuditLogEntry {
    #[serde(rename = "actionId", default, skip_serializing_if = "Option::is_none")]
    pub action_id: Option<String>,
    #[serde(
        rename = "activityId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub activity_id: Option<String>,
    #[serde(rename = "actorCUID", default, skip_serializing_if = "Option::is_none")]
    pub actor_cuid: Option<String>,
    #[serde(
        rename = "actorDisplayName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub actor_display_name: Option<String>,
    #[serde(
        rename = "actorImageUrl",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub actor_image_url: Option<String>,
    #[serde(rename = "actorUPN", default, skip_serializing_if = "Option::is_none")]
    pub actor_upn: Option<String>,
    #[serde(
        rename = "actorUserId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub actor_user_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub area: Option<String>,
    #[serde(
        rename = "authenticationMechanism",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub authentication_mechanism: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<decorated_audit_log_entry::Category>,
    #[serde(
        rename = "categoryDisplayName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub category_display_name: Option<String>,
    #[serde(
        rename = "correlationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub correlation_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "ipAddress", default, skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[serde(rename = "projectId", default, skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(
        rename = "projectName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub project_name: Option<String>,
    #[serde(
        rename = "scopeDisplayName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub scope_display_name: Option<String>,
    #[serde(rename = "scopeId", default, skip_serializing_if = "Option::is_none")]
    pub scope_id: Option<String>,
    #[serde(rename = "scopeType", default, skip_serializing_if = "Option::is_none")]
    pub scope_type: Option<decorated_audit_log_entry::ScopeType>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "userAgent", default, skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
}
pub mod decorated_audit_log_entry {
    use super::*;
    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub enum Category {
        #[serde(rename = "unknown")]
        Unknown,
        #[serde(rename = "modify")]
        Modify,
        #[serde(rename = "remove")]
        Remove,
        #[serde(rename = "create")]
        Create,
        #[serde(rename = "access")]
        Access,
        #[serde(rename = "execute")]
        Execute,
    }
    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub enum ScopeType {
        #[serde(rename = "unknown")]
        Unknown,
        #[serde(rename = "deployment")]
        Deployment,
        #[serde(rename = "enterprise")]
        Enterprise,
        #[serde(rename = "organization")]
        Organization,
        #[serde(rename = "project")]
        Project,
    }
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VssJsonCollectionWrapper {
    #[serde(flatten)]
    pub vss_json_collection_wrapper_base: VssJsonCollectionWrapperBase,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VssJsonCollectionWrapperBase {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditActionInfoList {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub value: Vec<AuditActionInfo>,
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditStreamList {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub value: Vec<AuditStream>,
}
