#!/usr/bin/env bash
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Exit on error
set -e

ADO_PROJECT_NAME=$1
ADO_USER_EMAIL=$2

usage () {
    echo "Usage:"
    echo "  ./run_all_examples <project_name> <user_email_address>"
}

if [ -z "$ADO_PROJECT_NAME" ];
then
    echo "Missing project name parameter"
    usage
    exit 1
fi

if [ -z "$ADO_USER_EMAIL" ];
then
    echo "Error: Missing user email address parameter"
    usage
    exit 1
fi

# Enable trace
set -x

cargo run --example build_list --features="build"
cargo run --example git_repo_get --features="git" $ADO_PROJECT_NAME
cargo run --example git_repo_list --features="git"
cargo run --example graph_query --features="graph" $ADO_USER_EMAIL
cargo run --example pipeline_preview --features="pipelines" $ADO_PROJECT_NAME
cargo run --example pipelines --features="pipelines" $ADO_PROJECT_NAME
cargo run --example service_endpoint --features="service_endpoint"
cargo run --example client_pipeline_policy --features="git"

echo "Done"
